// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDx9_VwzOLDfduMWqBUMWpfb-60CS8sLs',
    appId: '1:447215672547:web:89cf59624a2e566a1af9d6',
    messagingSenderId: '447215672547',
    projectId: 'chat-app-eae7b',
    authDomain: 'chat-app-eae7b.firebaseapp.com',
    storageBucket: 'chat-app-eae7b.appspot.com',
    measurementId: 'G-KBRWDMHBNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyConjOxxMqyf83Ik0fkyY3ifSpc0BxlKdw',
    appId: '1:447215672547:android:6ad6be7ffecf1f351af9d6',
    messagingSenderId: '447215672547',
    projectId: 'chat-app-eae7b',
    storageBucket: 'chat-app-eae7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMEPslpGheUB5YbwHdRmXhIPeBj-zZfLU',
    appId: '1:447215672547:ios:4f6da3d6b5d87df81af9d6',
    messagingSenderId: '447215672547',
    projectId: 'chat-app-eae7b',
    storageBucket: 'chat-app-eae7b.appspot.com',
    iosClientId: '447215672547-pmgd8oo9j952nc1dfrpojl64nl6sbgnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignupFirstUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMEPslpGheUB5YbwHdRmXhIPeBj-zZfLU',
    appId: '1:447215672547:ios:4f6da3d6b5d87df81af9d6',
    messagingSenderId: '447215672547',
    projectId: 'chat-app-eae7b',
    storageBucket: 'chat-app-eae7b.appspot.com',
    iosClientId: '447215672547-pmgd8oo9j952nc1dfrpojl64nl6sbgnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignupFirstUi',
  );
}
